import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from 'next/font/local'
import FacebookPixel from '@/components/FacebookPixel'
import { Suspense } from "react";
const pixelId = process.env.NEXT_PUBLIC_FACEBOOK_PIXEL_ID;




const myFont = localFont({
  src: '../public/ekkushe-lalshalu.ttf',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${myFont.className}`}
      >
     
          <Suspense fallback={null}>
          <FacebookPixel pixelId={pixelId} />
       
        </Suspense>
        
        <ClerkProvider>{children}</ClerkProvider>

   
      </body>
    </html>
  );
}
